### PR TITLE
Add Mac support

### PR DESCRIPTION
**Pull request by datalogics-kam**
Thanks for making the conan-doxygen project. We're using it at Datalogics, so I've gone ahead and answered the question of Mac support.

We're staying on 1.8.13 because Doxygen 1.8.14 requires libclang, but doesn't supply it.

If there's a better branch to point this at, please advise. Also, feel free to use these commits or modify them in any way that suits you.

- Extract the `.dmg` file.
- Improve the handling of `FindDoxygen.cmake`
- Be more specific about what's put into the package.
- Verify everything works with `conan create`

### CODE REVIEW

**Comment by Croydon** [comment]
Thank you so much!

I will have a look next week and run our tests etc 😄

**Review by a-teammate — APPROVED** [review]
Looks fine :)

**Review by Croydon — APPROVED** [review]
Local Linux & Windows tests are successfull and our macOS CI looks good as well.

**Comment by Fohlen** [comment]
I can verify that this also works on my OSX 👍 forgot to report back here but I tested it the other day

**Comment by Croydon** [comment]
Cross-References:
https://github.com/inexorgame/inexor-core/issues/385
https://github.com/conan-io/wishlist/issues/115

**Pull request merged**
